site_name: easy spider tool
site_description: 一些简易、好用的爬虫工具，减少代码与文件冗余，提升工作的效率和代码整洁度
repo_name: hanxinkong/easy-spider-tool
repo_url: https://github.com/hanxinkong/easy-spider-tool

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  palette_mode: auto

nav:
  - 首页: index.md
  - 时间/日期相关: example/date.md
  - json相关: example/jsons.md
  - hash摘要相关: example/hash.md
  - 正则匹配相关: example/re.md
  - 数据清洗/转换相关: example/data.md
  - 合法性验证相关: example/verify.md
  - decorator: example/decorator.md
  - 通知相关: example/notice.md
  - 更新日志: log.md